# =============================
# Автор: Agent1k
# связь со мной: Тг: @MonsteXD ДС #pasha211
# поддержка версий: 1.16+
# поддерживаемая java: 16
# =============================
settings:
  shulker:
    inventory-name: "&fИнвентарь &aшалкера"
    size: 27 # слоты шалкера
    LEFT: true # открытие только с ЛКМ
    RIGHT: false # открытие только с ПКМ
    shift_right: false # использовать ли при открытие шалкера шифт+пкм
  open-shulker: # каким будет шалкер когда открыт
    material: BARRIER
    name: "&cОткрытый шалкер"
  # Настройка авто подбора
  # true - подбираются только предметы из списка
  # false - подбираются все предметы
  shulker-auto-all-item: true
  # Список предметов, которые будут автоматически добавляться в шалкер
  # РАБОТАЕТ ТОЛЬОК ЕСЛИ shulker-auto-all-items: true
  shulker-auto:
    - DIAMOND
    - OBSIDIAN
  shulker-limit: 6 # сколько шалкеров можно держать в инвентаре
sound:
  addItemShulker:
    # Название звука который будет воспроизводиться при добавлении предмета в шалкер
    sound: "ENTITY_ITEM_PICKUP"
    # Высота тона звука
    pitch: 1.2
    # Громкость звука
    volume: 0.6
    # Включить или отключить звук при подборе предмета
    enabled: true